name: CI

on:
  push:
    branches: ["cloud-branch"]
  pull_request:
    branches: ["cloud-branch"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install -DskipTests
